import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import { SectionProvider } from "@/contexts/Section";
import { ChatProvider } from "@/contexts/ChatContext";
import ChatModal from "@/components/ChatModal";
import ChatButton from "@/components/ChatButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SectionProvider>
          <ChatProvider>
            <Navbar />
            <ChatModal />
            <ChatButton />
            {children}
          </ChatProvider>
        </SectionProvider>
      </body>
    </html>
  );
}
